package com.carelon.whe.constants

object BundleKeyConstants {
    const val EXTRA_IMPORT_MEDICINES_COUNT = "EXTRA_IMPORT_MEDICINES_COUNT"
    const val EXTRA_IMPORT_MEDICINES = "EXTRA_IMPORT_MEDICINES"
    const val EXTRA_IMPORT_MEDICINES_NOT_NOW = "EXTRA_IMPORT_MEDICINES_NOT_NOW"
    const val EXTRA_MEDICINE_REMINDER_ITEM = "EXTRA_MEDICINE_REMINDER_ITEM"
    const val MEDICINES_TO_DISPLAY_IN_DETAILS = "MEDICINES_TO_DISPLAY_IN_DETAILS"
    const val EXTRA_MEDICINE_REMINDER_TIME_SELECTED = "EXTRA_MEDICINE_REMINDER_TIME_SELECTED"
    const val EXTRA_ADD_MEDICATION_TRIGGERED_FROM = "EXTRA_ADD_MEDICATION_TRIGGERED_FROM"
    const val EXTRA_SHOW_EXISTING_REMINDER_LIST = "EXTRA_SHOW_EXISTING_REMINDER_LIST"
    const val EXTRA_MEDICINE_REMINDERS_LIST = "EXTRA_MEDICINE_REMINDERS_LIST"
    const val EXTRA_EDIT_MEDICINE_REMINDER = "EXTRA_EDIT_MEDICINE_REMINDER"
    const val EXTRA_USER_NAME = "EXTRA_USER_NAME"
    const val EXTRA_NEED_CONSENT = "EXTRA_NEED_CONSENT"
    const val EXTRA_ERROR_ITEM = "EXTRA_ERROR_ITEM"
    const val EXTRA_TOKEN = "EXTRA_TOKEN"
    const val EXTRA_DEVICE_ID = "EXTRA_DEVICE_ID"
    const val EXTRA_RISK_ID = "EXTRA_RISK_ID"
    const val EXTRA_USER_ID = "EXTRA_USER_ID"
    const val EXTRA_EMAIl = "EXTRA_EMAIl"
    const val EXTRA_FOCUS_AREA_ID = "EXTRA_FOCUS_AREA_ID"
}