package com.carelon.whe.constants

object PreferenceKeyConstants {
    const val IS_APP_INSTALLED = "IS_APP_INSTALLED"
    const val IS_NEW_PRESCRIPTION_READ = "IS_NEW_PRESCRIPTION_READ"
    const val IS_FEATURE_PAGE_SHOWN = "IS_FEATURE_PAGE_SHOWN"
    const val SAVED_MEDICATION = "SAVED_MEDICATION"
    const val ACCESS_TOKEN = "ACCESS_TOKEN"
    const val IS_EARLY_ACCESS_SHOWN = "IS_EARLY_ACCESS_SHOWN"
    const val KEY_SHOW_WELCOME_DIALOG = "KEY_SHOW_WELCOME_DIALOG"
    const val IS_PRIVACY_POLICY_SHOWN = "IS_PRIVACY_POLICY_SHOWN"
    const val IS_EMAIL_VERIFIED = "IS_EMAIL_VERIFIED"
    const val KEY_DAILY_CHECK_IN = "KEY_DAILY_CHECK_IN"
    const val IS_TRACK_STEP_ACTIVITY_STEP_COMPLETED = "IS_TRACK_STEP_ACTIVITY_STEP_COMPLETED"
    const val TRACK_MEDICINE_STATUS = "TRACK_MEDICINE_STATUS"
}